import { Inspection, School, Document, Evidence, FinalReport } from '@/types';

const schools: School[] = [
  {
    id: 'school-001',
    name: 'Delhi Public School, RK Puram',
    address: 'Sector XII, RK Puram',
    city: 'New Delhi',
    state: 'Delhi',
    zipCode: '110022',
    phone: '+91 11 2617 1217',
    email: 'principal@dpsrkp.net',
    principalName: 'Dr. Anil Kumar Sharma',
    schoolType: 'public',
    totalStudents: 4500,
    establishedYear: 1972,
    coordinates: { latitude: 28.5562, longitude: 77.1734 },
  },
  {
    id: 'school-002',
    name: 'Modern School, Barakhamba Road',
    address: 'Barakhamba Road',
    city: 'New Delhi',
    state: 'Delhi',
    zipCode: '110001',
    phone: '+91 11 2331 6380',
    email: 'info@modernschool.net',
    principalName: 'Mrs. Priya Gupta',
    schoolType: 'public',
    totalStudents: 3200,
    establishedYear: 1920,
    coordinates: { latitude: 28.6289, longitude: 77.2266 },
  },
  {
    id: 'school-003',
    name: 'St. Xavier\'s School, Raj Niwas Marg',
    address: 'Raj Niwas Marg',
    city: 'Delhi',
    state: 'Delhi',
    zipCode: '110054',
    phone: '+91 11 2396 2103',
    email: 'stxaviersdelhi@gmail.com',
    principalName: 'Fr. Joseph Fernandes',
    schoolType: 'private',
    totalStudents: 2800,
    establishedYear: 1960,
    coordinates: { latitude: 28.6562, longitude: 77.2380 },
  },
  {
    id: 'school-004',
    name: 'Don Bosco School, Alaknanda',
    address: 'Alaknanda Road',
    city: 'New Delhi',
    state: 'Delhi',
    zipCode: '110019',
    phone: '+91 11 2602 8373',
    email: 'dbsalaknanda@gmail.com',
    principalName: 'Bro. Joseph Thomas',
    schoolType: 'private',
    totalStudents: 2100,
    establishedYear: 1980,
    coordinates: { latitude: 28.5289, longitude: 77.2501 },
  },
  {
    id: 'school-005',
    name: 'Sardar Patel Vidyalaya',
    address: 'Lodi Estate',
    city: 'New Delhi',
    state: 'Delhi',
    zipCode: '110003',
    phone: '+91 11 2464 2047',
    email: 'spv@spvdelhi.org',
    principalName: 'Dr. Meera Reddy',
    schoolType: 'public',
    totalStudents: 1800,
    establishedYear: 1958,
    coordinates: { latitude: 28.5916, longitude: 77.2193 },
  },
  {
    id: 'school-006',
    name: 'Springdales School, Pusa Road',
    address: 'Pusa Road',
    city: 'New Delhi',
    state: 'Delhi',
    zipCode: '110005',
    phone: '+91 11 2573 1554',
    email: 'springdales@vsnl.com',
    principalName: 'Mrs. Ameeta Mulla Wattal',
    schoolType: 'public',
    totalStudents: 2500,
    establishedYear: 1955,
    coordinates: { latitude: 28.6425, longitude: 77.1789 },
  },
];


const generateDocuments = (inspectionId: string): Document[] => [
  {
    id: `doc-${inspectionId}-1`,
    inspectionId,
    type: 'registration',
    name: 'School Registration Certificate',
    fileUrl: 'https://example.com/docs/registration.pdf',
    fileType: 'pdf',
    status: 'verified',
    uploadedBy: 'School Admin',
    uploadedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    verifiedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    size: 2048000,
  },
  {
    id: `doc-${inspectionId}-2`,
    inspectionId,
    type: 'license',
    name: 'Operating License',
    fileUrl: 'https://example.com/docs/license.pdf',
    fileType: 'pdf',
    status: 'verified',
    uploadedBy: 'School Admin',
    uploadedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    verifiedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    size: 1536000,
  },
  {
    id: `doc-${inspectionId}-3`,
    inspectionId,
    type: 'insurance',
    name: 'Insurance Policy Document',
    fileUrl: 'https://example.com/docs/insurance.pdf',
    fileType: 'pdf',
    status: 'verified',
    uploadedBy: 'School Admin',
    uploadedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    verifiedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    size: 3072000,
  },
  {
    id: `doc-${inspectionId}-4`,
    inspectionId,
    type: 'safety_certificate',
    name: 'Fire Safety Certificate',
    fileUrl: 'https://example.com/docs/safety.pdf',
    fileType: 'pdf',
    status: Math.random() > 0.5 ? 'verified' : 'pending',
    uploadedBy: 'School Admin',
    uploadedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    verifiedAt: Math.random() > 0.5 ? new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString() : undefined,
    size: 1024000,
  },
  {
    id: `doc-${inspectionId}-5`,
    inspectionId,
    type: 'staff_qualification',
    name: 'Staff Qualification Records',
    fileUrl: 'https://example.com/docs/staff.pdf',
    fileType: 'pdf',
    status: 'pending',
    uploadedBy: 'School Admin',
    uploadedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    size: 4096000,
  },
];


const generateEvidence = (inspectionId: string): Evidence[] => [
  {
    id: `evidence-${inspectionId}-1`,
    inspectionId,
    type: 'photo',
    url: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=400',
    tag: 'classroom',
    description: 'Main classroom view',
    capturedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    capturedBy: 'Inspector Rajesh Kumar',
    fileSize: 2048000,
    isUploaded: true,
  },
  {
    id: `evidence-${inspectionId}-2`,
    inspectionId,
    type: 'photo',
    url: 'https://images.unsplash.com/photo-1562774053-701939374585?w=400',
    tag: 'lab',
    description: 'Science laboratory',
    capturedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    capturedBy: 'Inspector Rajesh Kumar',
    fileSize: 1843200,
    isUploaded: true,
  },
  {
    id: `evidence-${inspectionId}-3`,
    inspectionId,
    type: 'photo',
    url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400',
    tag: 'safety',
    description: 'Fire extinguisher installation',
    capturedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    capturedBy: 'Inspector Rajesh Kumar',
    fileSize: 1536000,
    isUploaded: true,
  },
];

export const dummyInspections: Inspection[] = [
  {
    id: 'insp-001',
    schoolId: 'school-001',
    school: schools[0],
    officerId: 'officer-001',
    status: 'document_verification',
    priority: 'high',
    assignedDate: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    isOverdue: false,
    documents: generateDocuments('insp-001'),
    evidence: generateEvidence('insp-001'),
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'insp-002',
    schoolId: 'school-002',
    school: schools[1],
    officerId: 'officer-001',
    status: 'assigned',
    priority: 'medium',
    assignedDate: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    dueDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    isOverdue: false,
    documents: generateDocuments('insp-002'),
    evidence: [],
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'insp-003',
    schoolId: 'school-003',
    school: schools[2],
    officerId: 'officer-001',
    status: 'pending',
    priority: 'urgent',
    assignedDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    dueDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    isOverdue: false,
    documents: generateDocuments('insp-003'),
    evidence: [],
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'insp-004',
    schoolId: 'school-004',
    school: schools[3],
    officerId: 'officer-001',
    status: 'in_progress',
    priority: 'medium',
    assignedDate: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    isOverdue: false,
    documents: generateDocuments('insp-004'),
    evidence: generateEvidence('insp-004'),
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'insp-005',
    schoolId: 'school-005',
    school: schools[4],
    officerId: 'officer-001',
    status: 'completed',
    priority: 'low',
    assignedDate: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    completedDate: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    dueDate: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    isOverdue: false,
    documents: generateDocuments('insp-005'),
    evidence: generateEvidence('insp-005'),
    finalReport: {
      id: 'report-005',
      inspectionId: 'insp-005',
      overallScore: 85,
      riskCategory: 'low',
      recommendation: 'approve',
      summary: 'School meets all required standards with minor improvements needed.',
      weaknesses: ['Minor sanitation issues', 'Limited lab equipment'],
      submittedAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
      submittedBy: 'Inspector Rajesh Kumar',
    },
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'insp-006',
    schoolId: 'school-006',
    school: schools[5],
    officerId: 'officer-001',
    status: 'assigned',
    priority: 'high',
    assignedDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    dueDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    isOverdue: true,
    documents: generateDocuments('insp-006'),
    evidence: [],
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export { schools };
